nonIdempotentAnnotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous
encryption:
  enabled: true
  type: wireguard
  nodeEncryption: true # Beta feature in 1.18.5. Turn off if any problems occur
kubeProxyReplacement: true
routingMode: native
ipv4NativeRoutingCIDR: 192.168.56.0/24
ipam:
  mode: kubernetes
gatewayAPI:
  enabled: true
  enableAlpn: true
  enableAppProtocol: true
l2announcements:
  enabled: true
  leaseDuration: 3s
  leaseRenewDeadline: 1s
  leaseRetryPeriod: 200ms
k8sServiceHost: localhost
k8sServicePort: "6443"
k8sClientRateLimit:
  qps: 30
  burst: 35
