apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-ha
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://charts.loft.sh
    targetRevision: 0.32.0-next.0
    chart: vcluster
    helm:
      releaseName: vcluster-team-01
      parameters:
        - name: "controlPlane.backingStore.etcd.deploy.enabled"
          value: "true"
        - name: "controlPlane.backingStore.etcd.deploy.statefulSet.highAvailability.replicas"
          value: "3"
        - name: "controlPlane.statefulSet.highAvailability.replicas"
          value: "3"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: team-01

