apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-resource-quota
  namespace: default
  labels:
    policy.admin.io/is-protected: "true"
spec:
  hard:
    requests.cpu: 1
    requests.memory: 2Gi
    limits.cpu: 4
    limits.memory: 4Gi
