apiVersion: v1
kind: ConfigMap
metadata:
  name: openldap-server
  namespace: default
data:
  LDAP_ORGANISATION: "vfde"
  LDAP_DOMAIN: "vfde.com"
  LDAP_ADMIN_PASSWORD: "admin"
  LDAP_TLS: "false"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: default
  labels:
    app: openldap
spec:
  selector:
    matchLabels:
      app: openldap
  replicas: 1
  template:
    metadata:
      labels:
        app: openldap
    spec:
      containers:
        - name: openldap
          image: "osixia/openldap:1.5.0"
          args:
            - --copy-service
            - --loglevel=debug
          ports:
            - containerPort: 389
              name: ldap
          volumeMounts:
            - name: ldifs
              mountPath: /container/service/slapd/assets/config/bootstrap/ldif/custom/ou-groups-and-users.ldif
              subPath: ou-groups-and-users.ldif
            - name: ldifs
              mountPath: /container/service/slapd/assets/config/bootstrap/ldif/custom/uid-admin.ldif
              subPath: uid-admin.ldif
            - name: ldifs
              mountPath: /container/service/slapd/assets/config/bootstrap/ldif/custom/acl.ldif
              subPath: acl.ldif
          envFrom:
            - configMapRef:
                name: openldap-server
      volumes:
        - name: ldifs
          configMap:
            name: ldifs
---
apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: default
spec:
  type: NodePort
  selector:
    app: openldap
  ports:
    - name: ldap
      protocol: TCP
      port: 389
      targetPort: ldap
