apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-agent
  namespace: monitoring
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: prometheus-agent
#   namespace: monitoring
# rules:
# - apiGroups: [""]
#   resources:
#   - services
#   - endpoints
#   - pods
#   verbs: ["get", "list", "watch"]
# - apiGroups: [""]
#   resources:
#   - configmaps
#   verbs: ["get"]
# - apiGroups:
#   - networking.k8s.io
#   resources:
#   - ingresses
#   verbs: ["get", "list", "watch"]
# - nonResourceURLs: ["/metrics"]
#   verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: prometheus-agent
  namespace: monitoring
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: PrometheusAgent
metadata:
  name: prometheus-agent
  namespace: monitoring
spec:
  replicas: 3
  replicaExternalLabelName: "prometheus_replica"
  scrapeInterval: 15s
  enableFeatures:
    - exemplar-storage
  serviceAccountName: prometheus-agent
  serviceMonitorSelector:
    matchLabels:
      serviceMonitorSelector: prometheus
  tsdb:
    # out of order error of cadvisor
    # see: https://github.com/prometheus/prometheus/issues/14973 
    outOfOrderTimeWindow: 1s
  remoteWrite:
    - url: http://receiver-write.monitoring.svc.cluster.local:10908/api/v1/receive
