apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: internet-egress
  labels:
    policy.admin.io/protected: "true"
spec:
  podSelector:
    matchLabels:
      networking.admin.io/allow-internet-egress: "true"
  egress:
    - {}
  policyTypes:
    - Egress
