apiVersion: policies.kyverno.io/v1
kind: ValidatingPolicy
metadata:
  name: block-operations-for-label-namespace
spec:
  failurePolicy: Fail
  validationActions:
    - Deny
  matchConstraints:
    resourceRules:
      - apiGroups: ["networking.k8s.io"]
        apiVersions: ["*"]
        resources: ["*"]
        operations: [UPDATE, DELETE]
  validations:
    - message: "Protected resources (teccle-group.io/is-protected: true) can only be updated or deleted by a cluster-admin."
      expression: >
        (
          has(oldObject.metadata.labels) ?
          !oldObject.metadata.labels.exists(l, l == 'teccle-group.io/is-protected'):
          true
        )
        ||
        (
          has(request.userInfo.groups) &&
          request.userInfo.groups.exists(g, g == 'cluster-admin') || request.userInfo.groups.exists(g, g == 'kubeadm:cluster-admins')
        )
