apiVersion: policies.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: block-label-namespace
spec:
  failurePolicy: Fail
  validationActions:
    - Deny
  matchConstraints:
    resourceRules:
      - apiGroups: ["*"]
        apiVersions: ["*"]
        operations: [CREATE, UPDATE]
        resources: ["*"]
  validations:
    - message: "admin.io/* labels are only allowed to be set for cluster-admin users"
      expression: >
        (
          has(request.userInfo.groups) &&
          request.userInfo.groups.exists(g, g == 'cluster-admin')
        )
        ||
        (
          has(object.metadata.labels) ?
          !object.metadata.labels.exists(k, k.matches('*admin.io.*')) :
          true
        )
